#logging:
#  level:
#    root: DEBUG

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 0

spring:
  cloud:
    stream:
      bindings:

        kinesis_test:
          destination: kinesis_test
          group: kinesis_test
          content-type: text/json
          consumer:
            concurrency: 2
            shardIteratorType: TRIM_HORIZON

        kinesis_test2:
          destination: kinesis_test2
          group: kinesis_test2
          content-type: text/json
          consumer:
            concurrency: 4
            shardIteratorType: TRIM_HORIZON

      kinesis:
        binder:
          checkpoint:
            table: SpringIntegrationMetadataStore
          auto-add-shards: false
          auto-create-stream: true
          locks:
            table: SpringIntegrationLockRegistry
#          kpl-kcl-enabled: true
#      instance-count: 2
#      instance-index: 2
